@host=https://localhost:7139

GET {{host}}/api/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNjI2NGQ5YS05MWUzLTQwNGMtOGQ0Yi00NWE1MmFkNTJiYTYiLCJnaXZlbl9uYW1lIjoiVHJ1b25nIiwiZmFtaWx5X25hbWUiOiJUaGFuaCBOaGFuIiwianRpIjoiNzBkNTU0OWYtYzdjMi00NTkzLWIyMGMtMWIxMmFhYzAyZDAwIiwiZXhwIjoxNzMxMDAwMzIzLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.gwaIUxQcvDivbjk28r9Sx_UpBdkrwfFOa6IAbmW0UmU