@host=https://localhost:7139

POST {{host}}/api/auth/register
Content-Type: application/json

{
    "firstName": "Truong",
    "lastName": "Thanh Nhan",
    "email": "truongthanhnhangv@gmail.com",
    "password": "hello"
}
